// Shared language list for source/target pickers (Upload page + Companion
// import). Kept in sync with the backend offline-NMT language map
// (translator.SUPPORTED_LANGUAGES / nmt_translator._FLORES_CODES). Any of
// these can be picked as a subtitle target — translation is never capped to
// a short list. Ordered roughly by region for an easier scan.
export const LANGUAGES = [
  { code: '', label: 'Auto-detect' },
  // Western European
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'it', label: 'Italian' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'nl', label: 'Dutch' },
  { code: 'ca', label: 'Catalan' },
  { code: 'gl', label: 'Galician' },
  { code: 'eu', label: 'Basque' },
  { code: 'ga', label: 'Irish' },
  { code: 'cy', label: 'Welsh' },
  { code: 'is', label: 'Icelandic' },
  { code: 'lb', label: 'Luxembourgish' },
  { code: 'mt', label: 'Maltese' },
  // Nordic
  { code: 'sv', label: 'Swedish' },
  { code: 'da', label: 'Danish' },
  { code: 'no', label: 'Norwegian' },
  { code: 'fi', label: 'Finnish' },
  // Slavic / Baltic / other Eastern European
  { code: 'ru', label: 'Russian' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'pl', label: 'Polish' },
  { code: 'cs', label: 'Czech' },
  { code: 'sk', label: 'Slovak' },
  { code: 'sl', label: 'Slovenian' },
  { code: 'hr', label: 'Croatian' },
  { code: 'sr', label: 'Serbian' },
  { code: 'bs', label: 'Bosnian' },
  { code: 'bg', label: 'Bulgarian' },
  { code: 'mk', label: 'Macedonian' },
  { code: 'be', label: 'Belarusian' },
  { code: 'ro', label: 'Romanian' },
  { code: 'hu', label: 'Hungarian' },
  { code: 'et', label: 'Estonian' },
  { code: 'lv', label: 'Latvian' },
  { code: 'lt', label: 'Lithuanian' },
  { code: 'sq', label: 'Albanian' },
  { code: 'el', label: 'Greek' },
  // Middle East / Caucasus / Central Asia
  { code: 'ar', label: 'Arabic' },
  { code: 'he', label: 'Hebrew' },
  { code: 'fa', label: 'Persian' },
  { code: 'tr', label: 'Turkish' },
  { code: 'az', label: 'Azerbaijani' },
  { code: 'kk', label: 'Kazakh' },
  { code: 'ky', label: 'Kyrgyz' },
  { code: 'uz', label: 'Uzbek' },
  { code: 'tg', label: 'Tajik' },
  { code: 'hy', label: 'Armenian' },
  { code: 'ka', label: 'Georgian' },
  { code: 'ku', label: 'Kurdish' },
  { code: 'ps', label: 'Pashto' },
  // South Asia
  { code: 'hi', label: 'Hindi' },
  { code: 'bn', label: 'Bengali' },
  { code: 'ur', label: 'Urdu' },
  { code: 'pa', label: 'Punjabi' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'mr', label: 'Marathi' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'kn', label: 'Kannada' },
  { code: 'ml', label: 'Malayalam' },
  { code: 'ne', label: 'Nepali' },
  { code: 'si', label: 'Sinhala' },
  { code: 'or', label: 'Odia' },
  { code: 'as', label: 'Assamese' },
  // East / Southeast Asia
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'zh', label: 'Chinese (Simplified)' },
  { code: 'zh-tw', label: 'Chinese (Traditional)' },
  { code: 'yue', label: 'Cantonese' },
  { code: 'vi', label: 'Vietnamese' },
  { code: 'th', label: 'Thai' },
  { code: 'id', label: 'Indonesian' },
  { code: 'ms', label: 'Malay' },
  { code: 'tl', label: 'Filipino' },
  { code: 'my', label: 'Burmese' },
  { code: 'km', label: 'Khmer' },
  { code: 'lo', label: 'Lao' },
  { code: 'jv', label: 'Javanese' },
  { code: 'su', label: 'Sundanese' },
  { code: 'mn', label: 'Mongolian' },
  // Africa
  { code: 'sw', label: 'Swahili' },
  { code: 'am', label: 'Amharic' },
  { code: 'ha', label: 'Hausa' },
  { code: 'yo', label: 'Yoruba' },
  { code: 'ig', label: 'Igbo' },
  { code: 'zu', label: 'Zulu' },
  { code: 'xh', label: 'Xhosa' },
  { code: 'sn', label: 'Shona' },
  { code: 'so', label: 'Somali' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'mg', label: 'Malagasy' },
  { code: 'ny', label: 'Chichewa' },
  { code: 'st', label: 'Sesotho' },
];
